# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire',
            field=models.DateTimeField(),
        ),
    ]
