# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20180727_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
