# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20180728_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.AddField(
            model_name='wish',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='wishlist.User'),
        ),
    ]
