# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20180728_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.AddField(
            model_name='wish',
            name='user',
            field=models.ManyToManyField(null=True, related_name='wishes', to='wishlist.User'),
        ),
    ]
