# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_auto_20180728_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='added_by',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
